In [3]:
import numpy as np

## ARRAY RESHAPING : 

In [ ]:

arr = np.arange(10)
print("Normal array : ", arr)

Normal array :  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# NOTE : 1) reshape(rows, columns) ==> this can convert a vector into matrices of any order if possible
reshaped_array = arr.reshape(2,5)
print("After reshaping the given array : \n", reshaped_array)

After reshaping the given array : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## difference between .flatten() and .ravel()

Use flatten() when:
You need a new, independent copy of the array and want to ensure the original data is never changed.
The highest performance is not a critical concern.


Use ravel() when:
You want the most memory-efficient and fastest way to flatten an array.
You are aware that changes to the returned array might affect the original data. 

In [ ]:
# NOTE : 2) flatten()       ---> This converts the matrices of particular order into a normal vector 

flattened_array = reshaped_array.flatten()
print(f"After flattening : \n", flattened_array)

After flattening : 
 [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# NOTE : 3) .ravel()---> This makes changes over the original

ravelled_array = flattened_array.ravel()
print(f"The ravelled_array is : ",ravelled_array)


The ravelled_array is :  [0 1 2 3 4 5 6 7 8 9]
After flattening :  [0 1 2 3 4 5 6 7 8 9]


## Some array opearation

 # SLICING OF ARRAY

In [ ]:
#NOTE : basic slicing of the array
import numpy as np

array_1D = np.arange(10)
print("Array_1D : ",array_1D)
print("Basic slicing : ", array_1D[1:9:2])      #(startIndex : endIndex : step)


Array_1D :  [0 1 2 3 4 5 6 7 8 9]
Basic slicing :  [1 3 5 7]


In [ ]:
#NOTE : negative slicing concept revision : 

print("negative slicing : ", array_1D[-5])

negative slicing :  5


### slicing of 2D and 3D array

# for multi- dimensional matrices we need to give index of both rows and columns .
# the count of the rows will be form 0th rows to nth . Similarly the count of the 
# columns will also be same as rows

In [5]:
import numpy as np
Array_2D = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
#To select element - 5 from above matrice

#NOTE : IN normal python nested list doesn't supports multidimensional slicing
#NOTE : while in numpy's arrays since arrays are multi dimensional so, they supports slicing so, we can slice 
#       through each axis using commas(,)
#  
print("Specific element : ", Array_2D[1, 1])      # (rows and column)

#----------------------------------------------------------------------------
# NOTE : to select whole rows

print(" for example Entire 3rd row : ", Array_2D[2])

#----------------------------------------------------------------------------
#NOTE : to select whole column

print(" for example Entire 2nd column : ", Array_2D[:, 1])


Specific element :  5
 for example Entire 3rd row :  [7 8 9]
 for example Entire 2nd column :  [2 5 8]


### Sorting in numpy

# NOTE : here we use a special numpy method to sort the 1D or 2D vector or matrices respectively

In [ ]:
#NOTE : sorting 1D array
Array_1D = np.array([5, 2, 3, 6])
print("Sorting 1D array : ", np.sort(Array_1D))

Sorting 1D array :  [2 3 5 6]


In [10]:
#NOTE : sorting 2D array according to columns
Array_2D = np.array([[6,2,3],
                     [8,5,1],
                     [7,4,9]])
print("Sorting 2D array : ", np.sort(Array_2D, axis=0))

Sorting 2D array :  [[6 2 1]
 [7 4 3]
 [8 5 9]]


In [11]:
#NOTE : sorting 2D array according to rows
Array_2D = np.array([[6,2,3],
                     [8,5,1],
                     [7,4,9]])
print("Sorting 2D array : ", np.sort(Array_2D, axis=1))

Sorting 2D array :  [[2 3 6]
 [1 5 8]
 [4 7 9]]


# axis = 0 ---> means sorting columns wise
# axis = 1 ---> means sorting rows wise

## Filtering 

In [ ]:
#NOTE : here we can use the conditions like this 
number = np.array([1,2,3,4,5,6,7,8,9])
even_only = number[number % 2 == 0]
print("Even number list : ", even_only)

Even number list :  [2 4 6 8]


## filter with mask : 
        mask is just a expression that evaluates for eg: conditions
        FOR Eg : 

In [ ]:
mask = number > 6       # ---> so this is an expression (mask)
print("List of no. greater than 6 : ", number[mask])

List of no. greater than 6 :  [7 8 9]


### Fancy Indexing and np.where()

In [6]:
indices = [3, 1, 7]     # these are the indexes of the elements which we want
print("Number of indexes(3,1,7) : ", number[indices])

Number of indexes(3,1,7) :  [4 2 8]


# There are two cases of np.where():

1) single parameter : in this case, we use a single condition and this returns indices of elements in the form of expressions not exactly as list .But we can format this using zip.

2) 3 - Argument form : here , we have np.where(condition , x , y) so, if the condition is 
    True then it selects elements from x and if False then selects from y
    This doesn't gives output in the form of expression hence, we can directly print it.

In [ ]:
#NOTE : case 1

where_result = np.where(number > 4)
print("np.where() result : ", where_result) # this will show expression not exact result

np.where() result :  (array([4, 5, 6, 7, 8]),)


In [ ]:
# NOTE : case 2 --> this don't give output in the form of expressions as in case 1

# if condition is false then, it will put the element as unused as it is ! 
where_result_case2 = np.where(number > 4, number * 2, number)
print("where_result_case2 : ", where_result_case2)

where_result_case2 :  [ 1  2  3  4 10 12 14 16 18]


### Array Adding and removing : 

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

adding_eachElements_array = arr1 + arr2    #NOTE : This is wrong way. This will add corresponding elements
combined = np.concatenate((arr1, arr2))
print("Adding corresponding elements : ", adding_eachElements_array)
print("combining : ", combined)


Adding corresponding elements :  [5 7 9]
combining :  [1 2 3 4 5 6]


### Compatibility shapes of an array : 

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# Shapes of array = a
print("Shapes of array a : ", a.shape)

# Shapes of array = b
print("Shapes of array b : ", b.shape)

# Shapes of array = c
print("Shapes of array c : ", c.shape)

# NOTE : we can check the shape of the arrays 
print("Compatibility shpaes : ", a.shape == b.shape == c.shape)
 

Shapes of array a :  (3,)
Shapes of array b :  (3,)
Shapes of array c :  (3,)
Compatibility shpaes :  True


###     Insertion of rows and column : 

In [25]:
original = np.array([[1,2],
                     [3,5]])

row_to_add = np.array([4, 7])
col_to_add = np.array([[8], [9]]) 
# this goes top to button per element 8 to top and 9 to buttom


#NOTE : adding new row to original
original_with_new_row = np.vstack((original, row_to_add))
print("Before adding new row : \n", original)
print("\n")
print("Original with new row : \n", original_with_new_row )
print("\n")

#NOTE : adding new colum to original
original_with_new_col = np.hstack((original, col_to_add))
print("Original with new column : \n", original_with_new_col)

Before adding new row : 
 [[1 2]
 [3 5]]


Original with new row : 
 [[1 2]
 [3 5]
 [4 7]]


Original with new column : 
 [[1 2 8]
 [3 5 9]]


### Array deletion : 
Syntax : np.delete(start, stop , step)
            Or,
         np.delete(array , index)

In [26]:
arr = np.array([1, 3 ,4, 5, 6, 9])
deleted_array = np.delete(arr, 2)
print("Array after deleting element of index 2 : ", deleted_array)

Array after deleting element of index 2 :  [1 3 5 6 9]
