## ARRAY RESHAPING : 

In [ ]:

arr = np.arange(10)
print("Normal array : ", arr)

Normal array :  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# NOTE : 1) reshape(rows, columns) ==> this can convert a vector into matrices of any order if possible
reshaped_array = arr.reshape(2,5)
print("After reshaping the given array : \n", reshaped_array)

After reshaping the given array : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## difference between .flatten() and .ravel()

Use flatten() when:
You need a new, independent copy of the array and want to ensure the original data is never changed.
The highest performance is not a critical concern.


Use ravel() when:
You want the most memory-efficient and fastest way to flatten an array.
You are aware that changes to the returned array might affect the original data. 

In [ ]:
# NOTE : 2) flatten()       ---> This converts the matrices of particular order into a normal vector 

flattened_array = reshaped_array.flatten()
print(f"After flattening : \n", flattened_array)

After flattening : 
 [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# NOTE : 3) .ravel()---> This makes changes over the original

ravelled_array = flattened_array.ravel()
print(f"The ravelled_array is : ",ravelled_array)


The ravelled_array is :  [0 1 2 3 4 5 6 7 8 9]
After flattening :  [0 1 2 3 4 5 6 7 8 9]


## Some array opearation

 # SLICING OF ARRAY

In [ ]:
#NOTE : basic slicing of the array
import numpy as np

array_1D = np.arange(10)
print("Array_1D : ",array_1D)
print("Basic slicing : ", array_1D[1:9:2])      #(startIndex : endIndex : step)


Array_1D :  [0 1 2 3 4 5 6 7 8 9]
Basic slicing :  [1 3 5 7]


In [ ]:
#NOTE : negative slicing concept revision : 

print("negative slicing : ", array_1D[-5])

negative slicing :  5


### slicing of 2D and 3D array

# for multi- dimensional matrices we need to give index of both rows and columns .
# the count of the rows will be form 0th rows to nth . Similarly the count of the 
# columns will also be same as rows

In [ ]:
Array_2D = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
#To select element - 5 from above matrice
print("Specific element : ", Array_2D[1, 1])      # (rows and column)

Specific element :  5
