In [2]:
import numpy as np
import matplotlib.pyplot as mat

In [12]:
#data structures : [restaurant_id, 2021, 2022, 2023, 2024]
# This is data of world's 5 famous restaurant

restaurants_data = np.array([
    [375, 3, 40, 25, 96],   # Noma (Denmark)
    [420, 3, 50, 30, 98],   # Osteria Francescana (Italy)
    [390, 2, 60, 28, 94],   # Eleven Madison Park (USA)
    [310, 2, 45, 22, 92],   # Central (Peru)
    [450, 3, 55, 35, 99]    # Mirazur (France)
])

print(f"The dimension of above data : {restaurants_data.ndim}D")
print(f"The shape of above data : {restaurants_data.shape}")
#NOTE : accessing first 3 restaurant data
print("First 3 - data : \n", restaurants_data[0:3])
print("\n")
print("restaurant data without id : \n", restaurants_data[:, 1:])
print("\n")



The dimension of above data : 2D
The shape of above data : (5, 5)
First 3 - data : 
 [[375   3  40  25  96]
 [420   3  50  30  98]
 [390   2  60  28  94]]


restaurant data without id : 
 [[ 3 40 25 96]
 [ 3 50 30 98]
 [ 2 60 28 94]
 [ 2 45 22 92]
 [ 3 55 35 99]]




In [11]:
#NOTE : total shales of each restaurants : 
#NOTE : array[row_start:row_end : row_step , column_start:column_end : column_step]

total_year_sales = np.sum(restaurants_data[:, 1:], axis=1)
print("Total sales of 5 company for year 2021 : \n", total_year_sales)

Total sales of 5 company for year 2021 : 
 [164 181 184 161 192]


In [ ]:
#NOTE : Minimum sales of each company 

min_sales = np.min(restaurants_data[:, 1:], axis=1)
print("The minimum sales of each of the 5 company among year 2021, 2022, 2023 and 2024 : \n"
      ,min_sales)

The minimum sales of each of the 5 company among year 2021, 2022, 2023 and 2024 : 
 [3 3 2 2 3]


In [ ]:
#NOTE :  Maximum sales per year

max_sales = np.max(restaurants_data[:, 1:], axis=0)
print("Maximum sales among 5 company every year : \n", max_sales)

Maximum sales among 5 company every year : 
 [ 3 60 35 99]


In [23]:
#NOTE : Average sales of each restaurant after 2021, 2022, 2023, 2024

avg_sales = np.average(restaurants_data[:, 1:], axis=1)
print("Average sales of all 5 company : \n", avg_sales) # this won't show digit after decimal
print("\n")
#NOTE : formating the result
for i, avg in enumerate(avg_sales, start=1):
    print(f"Average sale of restaurant {i} : {avg:.2f}")

Average sales of all 5 company : 
 [41.   45.25 46.   40.25 48.  ]


Average sale of restaurant 1 : 41.00
Average sale of restaurant 2 : 45.25
Average sale of restaurant 3 : 46.00
Average sale of restaurant 4 : 40.25
Average sale of restaurant 5 : 48.00


In [24]:
#NOTE : Finding cummulative sales of each company : 

cummu_sale = np.cumsum(restaurants_data[:, 1:], axis=1)
for i, cummulative_sale in enumerate(cummu_sale, start=1):
    print(f"Cummulative sales of Restaurant {i} : ", cummulative_sale)

Cummulative sales of Restaurant 1 :  [  3  43  68 164]
Cummulative sales of Restaurant 2 :  [  3  53  83 181]
Cummulative sales of Restaurant 3 :  [  2  62  90 184]
Cummulative sales of Restaurant 4 :  [  2  47  69 161]
Cummulative sales of Restaurant 5 :  [  3  58  93 192]


### Vector operation in numpy

In [25]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([1, 2, 3])

#NOTE : Vector addition 
print("Vector addition : ", vec1 + vec2)


Vector addition :  [2 4 6]


In [27]:
#NOTE : Vector multiplication
print("Vector multiplication : ", vec1 * vec2)

Vector multiplication :  [1 4 9]


In [28]:
#NOTE : Vector subtraction : 
print("Vector subtraction : ", vec1 - vec2)

Vector subtraction :  [0 0 0]


In [ ]:
#NOTE : Dot product  : For this, we use a numpy method np.dot(vec1, vec2)
# we know : if a = (a1, a2) and b = (b1, b2)
        #   a.b = a1.b1 + a2.b2        --->     2D vector dot product

print("Dot product of vector-1 and vector-2 : ", np.dot(vec1, vec2))

Dot product of vector-1 and vector-2 :  14


### finding angle between 2 - vectors:
        for this we use the same formula we use mathematically but to calculate the magnitude there is special methods and similarly for trigonometric ratios we have methods.

In [32]:
angle = np.arccos(np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec1)))
print(f"The angle between vec1 and vec2 : {angle} degree")

The angle between vec1 and vec2 : 0.0 degree


### vectorized :
 basically means making anything able to broadcasts(apply changes on each at a same time)
        for eg : if i had used for loop i had to go through one by one for array elements 
        But with the help of vectorize feature we can do easily.

        here below, np.vectorize() ==> is just a numpy method and 
        str.upper ===> is one of the property for string like we have lower for lowercase, 
        capitalize for capital

In [5]:
restaurants_types = np.array(['biryani', 'chinese', 'pizza', 'burger', 'cafe'])
vectorized_uppercase = np.vectorize(str.upper)
print("Vectorized_uppercase of above array : ", vectorized_uppercase(restaurants_types))
print("\n")
vectorized_uppercase = np.vectorize(str.lower)
print("Vectorized_lowercase of above array : ", vectorized_uppercase(restaurants_types))
print("\n")
vectorized_uppercase = np.vectorize(str.capitalize)
print("Vectorized_capital of above array : ", vectorized_uppercase(restaurants_types))

Vectorized_uppercase of above array :  ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


Vectorized_lowercase of above array :  ['biryani' 'chinese' 'pizza' 'burger' 'cafe']


Vectorized_capital of above array :  ['Biryani' 'Chinese' 'Pizza' 'Burger' 'Cafe']
